# Generated by Django 4.1.4 on 2023-01-13 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_alter_order_id_datamanagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
