# Generated by Django 4.1.4 on 2023-01-13 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_product_product_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('product_num', 'product_name')},
        ),
    ]
