# Generated by Django 4.1.4 on 2023-01-13 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_product_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='datamanagement',
            unique_together={('order', 'product')},
        ),
    ]
