# Generated by Django 4.1.4 on 2023-01-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_datamanagement_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_num',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_num',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
